version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16 # Specify a version for better stability
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678} # Better to use env vars
      POSTGRES_DB: ${POSTGRES_DB:-postgres} # Add database name
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Make port configurable
    networks:
      - postgres
    restart: unless-stopped
    healthcheck: # Add health check
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-12345678}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on: # Make sure postgres starts first
      postgres:
        condition: service_healthy

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
